### ISSUE TITLE
Compilation errors on Xcode 9.0 beta 3

### ISSUE THREAD

**Issue by kbmeister** [longbai/iOS-netdiag#5]
Using the newly released Xcode 9 beta 3, and the 'QNNetDiag' cocoapod, it fails to compile due to errors with macros.  CocoaLumberjack has had to deal with [a compile issue](https://github.com/CocoaLumberjack/CocoaLumberjack/issues/882) from this new Xcode beta as well. 

![screen shot 2017-07-21 at 3 22 35 pm](https://user-images.githubusercontent.com/10535911/28484733-fa3bd1e6-6e28-11e7-8a6f-671be78295e4.png)

**Comment by helinyu** [comment]
i meet this error too, how to fix it ? And i Updatee it to 0.0.4 version;

**Comment by jackrex** [comment]
same issues

**Comment by escrafford** [comment]
I just added a pull request to resolve this problem.

**Comment by longbai** [comment]
thanks for @escrafford  👍
