### ISSUE TITLE
xcode9 编译不过 （错了，是另外一个库PLMediaStreamingKit的原因）

### ISSUE THREAD

**Issue by jabez1314** [longbai/iOS-netdiag#9]
报错方法
select
check_compile_time

**Comment by Liuhuan247** [comment]
没人解决这个问题吗？

**Comment by lovelyBigTiger** [comment]
请问怎么解决的？我也是这个问题

**Comment by heyange2002** [comment]
同样的问题， 报“Expected parameter declarator”

check_compile_time(sizeof(IPHeader) == 20);
check_compile_time(offsetof(IPHeader, versionAndHeaderLength) == 0);
check_compile_time(offsetof(IPHeader, differentiatedServices) == 1);
check_compile_time(offsetof(IPHeader, totalLength) == 2);
check_compile_time(offsetof(IPHeader, identification) == 4);
check_compile_time(offsetof(IPHeader, flagsAndFragmentOffset) == 6);
check_compile_time(offsetof(IPHeader, timeToLive) == 8);
check_compile_time(offsetof(IPHeader, protocol) == 9);
check_compile_time(offsetof(IPHeader, headerChecksum) == 10);
check_compile_time(offsetof(IPHeader, sourceAddress) == 12);
check_compile_time(offsetof(IPHeader, destinationAddress) == 16);

**Comment by forrest-mao** [comment]
@Liuhuan247 @lovelyBigTiger @heyange2002 
可以升级到 0.0.6 版本解决这个问题，https://github.com/qiniu/iOS-netdiag/releases

**Comment by wangyingbo** [comment]
刚解决过了，check_compile_time 改为 __Check_Compile_Time可以解决。
